import datetime

from flask import Blueprint, jsonify, redirect, render_template, request, session, url_for

from extensions import get_db, login_required
from services.gemini import GeminiError, call_gemini
from services.prompts import build_chat_system_prompt

chat_bp = Blueprint("chat", __name__)


def _load_profile(db, student_id):
    row = db.execute(
        """
        SELECT s.email, p.qualification, p.grade, p.profession, p.destination, p.city, p.salary, p.score, p.ratio
        FROM students s
        LEFT JOIN student_profiles p ON p.student_id = s.id
        WHERE s.id = ?
        """,
        (student_id,),
    ).fetchone()
    return dict(row) if row else None


def _load_history(db, student_id, limit=40):
    rows = db.execute(
        "SELECT role, content FROM chat_messages WHERE student_id = ? ORDER BY id ASC LIMIT ?",
        (student_id, limit),
    ).fetchall()
    return [{"role": r["role"], "content": r["content"]} for r in rows]


def _save_message(db, student_id, role, content):
    db.execute(
        "INSERT INTO chat_messages (student_id, role, content, created_at) VALUES (?, ?, ?, ?)",
        (student_id, role, content, datetime.datetime.utcnow().isoformat()),
    )
    db.commit()


@chat_bp.route("/chat")
@login_required
def chat_page():
    student_id = session["student_id"]
    db = get_db()
    onboarded = db.execute("SELECT onboarded FROM students WHERE id = ?", (student_id,)).fetchone()
    if onboarded is not None and not onboarded["onboarded"]:
        return redirect(url_for("social.onboarding"))
    profile = _load_profile(db, student_id)
    history = _load_history(db, student_id)

    # The opening greeting is generated by a follow-up JS call to
    # /api/chat/opening after the page loads, NOT here. Some destinations'
    # knowledge base is large (e.g. the UK KB alone is ~650K characters), so
    # generating it can take well over the ~30s request timeout a production
    # WSGI server (gunicorn etc.) enforces by default -- blocking the page
    # render on that call means the whole page fails to load, not just the
    # greeting. Rendering immediately and fetching the greeting asynchronously
    # means a slow/failed AI call degrades to a retry button, not a dead page.
    needs_opening = not history

    return render_template("chat.html", profile=profile, messages=history, needs_opening=needs_opening)


@chat_bp.route("/api/chat/opening", methods=["POST"])
@login_required
def api_chat_opening():
    student_id = session["student_id"]
    db = get_db()
    history = _load_history(db, student_id)

    if history:
        # Already generated (e.g. a retry after the page was already seeded,
        # or a second tab) -- just hand back what exists instead of asking
        # Amara to "open" a second time.
        return jsonify({"ok": True, "reply": history[-1]["content"]})

    profile = _load_profile(db, student_id)
    system_prompt = build_chat_system_prompt(profile, opening=True)
    # Gemini's API rejects an empty `contents` array, so a minimal trigger
    # turn is sent (never persisted to chat_messages) -- the actual "open
    # proactively" instruction lives in the system prompt itself.
    trigger_history = [{"role": "user", "content": "(The student has just arrived. Please open.)"}]
    try:
        opening_reply = call_gemini(system_prompt, trigger_history, timeout=90)
    except GeminiError as exc:
        return jsonify({"ok": False, "error": str(exc)}), 502

    _save_message(db, student_id, "model", opening_reply)
    return jsonify({"ok": True, "reply": opening_reply})


@chat_bp.route("/api/chat", methods=["POST"])
@login_required
def api_chat():
    student_id = session["student_id"]
    payload = request.get_json(silent=True) or {}
    message = (payload.get("message") or "").strip()
    if not message:
        return jsonify({"ok": False, "error": "Message cannot be empty."}), 400

    db = get_db()
    profile = _load_profile(db, student_id)
    history = _load_history(db, student_id)

    # Save the user's turn before calling the AI so a mid-call failure doesn't
    # lose what they typed.
    _save_message(db, student_id, "user", message)
    history = history + [{"role": "user", "content": message}]

    system_prompt = build_chat_system_prompt(profile, opening=False)
    try:
        reply = call_gemini(system_prompt, history, timeout=90)
    except GeminiError as exc:
        return jsonify({"ok": False, "error": str(exc)}), 502

    _save_message(db, student_id, "model", reply)
    return jsonify({"ok": True, "reply": reply})
