import datetime

from flask import Blueprint, jsonify, redirect, render_template, request, session, url_for

from extensions import get_db, login_required
from services.gemini import GeminiError, call_gemini
from services.prompts import build_chat_system_prompt, strip_needs_human_marker

chat_bp = Blueprint("chat", __name__)


def _load_profile(db, student_id):
    row = db.execute(
        """
        SELECT s.email, p.qualification, p.grade, p.profession, p.destination, p.city, p.salary, p.score, p.ratio
        FROM students s
        LEFT JOIN student_profiles p ON p.student_id = s.id
        WHERE s.id = ?
        """,
        (student_id,),
    ).fetchone()
    return dict(row) if row else None


def _load_history(db, student_id, limit=40):
    rows = db.execute(
        "SELECT id, role, content FROM chat_messages WHERE student_id = ? ORDER BY id ASC LIMIT ?",
        (student_id, limit),
    ).fetchall()
    return [{"id": r["id"], "role": r["role"], "content": r["content"]} for r in rows]


def _save_message(db, student_id, role, content):
    cur = db.execute(
        "INSERT INTO chat_messages (student_id, role, content, created_at) VALUES (?, ?, ?, ?)",
        (student_id, role, content, datetime.datetime.utcnow().isoformat()),
    )
    db.commit()
    return cur.lastrowid


# Amara-facing reasons a conversation lands in the queue. "manual" (an admin
# flagging a conversation themselves) isn't wired up anywhere yet, but the
# column supports it without a schema change later.
REASON_AI_FALLBACK = "ai_fallback"


def _flag_for_human(db, student_id, reason=REASON_AI_FALLBACK):
    """Adds student_id to the handoff queue (skips if already open there --
    Amara hitting her fallback line twice in one conversation shouldn't
    create duplicate queue entries) and tells the student a counsellor has
    been notified. Does NOT pause Amara -- see chat_mode in api_chat for
    that; landing in the queue and a human actually taking over are two
    separate things, so the student is never left waiting on a human who
    might not look at the queue for hours."""
    existing = db.execute(
        "SELECT id FROM human_handoff_queue WHERE student_id = ? AND status = 'open'", (student_id,)
    ).fetchone()
    if existing:
        return
    now = datetime.datetime.utcnow().isoformat()
    db.execute(
        "INSERT INTO human_handoff_queue (student_id, reason, status, created_at) VALUES (?, ?, 'open', ?)",
        (student_id, reason, now),
    )
    db.commit()
    _save_message(
        db, student_id, "system",
        "🔔 A TGM counsellor has been notified about this conversation and will follow up here.",
    )


@chat_bp.route("/chat")
@login_required
def chat_page():
    student_id = session["student_id"]
    db = get_db()
    student = db.execute("SELECT onboarded, chat_mode FROM students WHERE id = ?", (student_id,)).fetchone()
    if student is not None and not student["onboarded"]:
        return redirect(url_for("social.onboarding"))
    profile = _load_profile(db, student_id)
    history = _load_history(db, student_id)
    last_id = history[-1]["id"] if history else 0

    # The opening greeting is generated by a follow-up JS call to
    # /api/chat/opening after the page loads, NOT here. Some destinations'
    # knowledge base is large (e.g. the UK KB alone is ~650K characters), so
    # generating it can take well over the ~30s request timeout a production
    # WSGI server (gunicorn etc.) enforces by default -- blocking the page
    # render on that call means the whole page fails to load, not just the
    # greeting. Rendering immediately and fetching the greeting asynchronously
    # means a slow/failed AI call degrades to a retry button, not a dead page.
    needs_opening = not history

    return render_template(
        "chat.html", profile=profile, messages=history, needs_opening=needs_opening,
        last_id=last_id, chat_mode=(student["chat_mode"] if student else "ai"),
    )


@chat_bp.route("/api/chat/opening", methods=["POST"])
@login_required
def api_chat_opening():
    student_id = session["student_id"]
    db = get_db()
    history = _load_history(db, student_id)

    if history:
        # Already generated (e.g. a retry after the page was already seeded,
        # or a second tab) -- just hand back what exists instead of asking
        # Amara to "open" a second time.
        last = history[-1]
        return jsonify({"ok": True, "reply": last["content"], "reply_message_id": last["id"]})

    profile = _load_profile(db, student_id)
    system_prompt = build_chat_system_prompt(profile, opening=True)
    # Gemini's API rejects an empty `contents` array, so a minimal trigger
    # turn is sent (never persisted to chat_messages) -- the actual "open
    # proactively" instruction lives in the system prompt itself.
    trigger_history = [{"role": "user", "content": "(The student has just arrived. Please open.)"}]
    try:
        opening_reply = call_gemini(system_prompt, trigger_history, timeout=90)
    except GeminiError as exc:
        return jsonify({"ok": False, "error": str(exc)}), 502

    opening_reply, needs_human = strip_needs_human_marker(opening_reply)
    reply_id = _save_message(db, student_id, "model", opening_reply)
    if needs_human:
        _flag_for_human(db, student_id)
    return jsonify({"ok": True, "reply": opening_reply, "reply_message_id": reply_id})


@chat_bp.route("/api/chat", methods=["POST"])
@login_required
def api_chat():
    student_id = session["student_id"]
    payload = request.get_json(silent=True) or {}
    message = (payload.get("message") or "").strip()
    if not message:
        return jsonify({"ok": False, "error": "Message cannot be empty."}), 400

    db = get_db()
    student = db.execute("SELECT chat_mode FROM students WHERE id = ?", (student_id,)).fetchone()
    chat_mode = student["chat_mode"] if student else "ai"

    # Save the user's turn before doing anything else so a mid-call failure
    # (or a human not replying immediately) never loses what they typed.
    user_msg_id = _save_message(db, student_id, "user", message)

    if chat_mode == "human":
        # A counsellor has taken this conversation over -- Amara stays
        # silent here. The counsellor sees the message in the admin inbox
        # and replies from there; the student's page picks it up via
        # polling (see /api/chat/poll), not this response.
        return jsonify({"ok": True, "reply": None, "mode": "human", "user_message_id": user_msg_id})

    profile = _load_profile(db, student_id)
    history = _load_history(db, student_id)
    # Gemini's API only accepts role "user"/"model" -- "system" notices
    # ("a counsellor has been notified") aren't part of the conversation and
    # are dropped, and a counsellor's own reply counts as the assistant's
    # turn (role "model") so Amara has full context if she's handed back.
    gemini_history = [
        {"role": "model" if h["role"] in ("model", "counsellor") else "user", "content": h["content"]}
        for h in history if h["role"] != "system"
    ]

    system_prompt = build_chat_system_prompt(profile, opening=False)
    try:
        reply = call_gemini(system_prompt, gemini_history, timeout=90)
    except GeminiError as exc:
        return jsonify({"ok": False, "error": str(exc)}), 502

    reply, needs_human = strip_needs_human_marker(reply)
    reply_id = _save_message(db, student_id, "model", reply)
    if needs_human:
        _flag_for_human(db, student_id)
    return jsonify({
        "ok": True, "reply": reply, "mode": "ai",
        "user_message_id": user_msg_id, "reply_message_id": reply_id,
    })


@chat_bp.route("/api/chat/poll")
@login_required
def api_chat_poll():
    """Picks up messages that arrived without the student's own request --
    a counsellor's live reply, or the "notified a counsellor" system notice.
    Scoped to session['student_id'] only; the `since` id is never trusted
    across students."""
    student_id = session["student_id"]
    since = request.args.get("since", type=int, default=0)
    db = get_db()
    rows = db.execute(
        "SELECT id, role, content FROM chat_messages WHERE student_id = ? AND id > ? AND role != 'user' ORDER BY id ASC",
        (student_id, since),
    ).fetchall()
    mode_row = db.execute("SELECT chat_mode FROM students WHERE id = ?", (student_id,)).fetchone()
    return jsonify({
        "ok": True,
        "mode": mode_row["chat_mode"] if mode_row else "ai",
        "messages": [{"id": r["id"], "role": r["role"], "content": r["content"]} for r in rows],
    })
