"""One-time conversion: ports Desktop/Counselor/knowledge/*.js (JS template-literal
string constants) into services/knowledge_base.py (Python string constants).

Not live-synced -- if the JS knowledge base is edited later, re-run this script to
refresh services/knowledge_base.py. Source of truth for the actual knowledge text
is Desktop/Counselor/knowledge/*.js; this script only mechanically re-encodes it.
"""
import os
import re

COUNSELOR_KB_DIR = r"C:\Users\TGM Education Abuja1\Desktop\Counselor\knowledge"
OUT_PATH = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "services", "knowledge_base.py")

FILES = [
    ("general.js", "KB_GENERAL"),
    ("uk.js", "KB_UK"),
    ("canada.js", "KB_CANADA"),
    ("ireland.js", "KB_IRELAND"),
    ("poland.js", "KB_POLAND"),
    ("germany.js", "KB_GERMANY"),
    ("usa.js", "KB_USA"),
    ("australia.js", "KB_AUSTRALIA"),
    ("document-generation.js", "KB_DOC_GEN"),
]

TRIPLE = '"""'


def extract(js_text, const_name):
    m = re.search(r"const\s+" + re.escape(const_name) + r"\s*=\s*`", js_text)
    if not m:
        raise ValueError(f"Could not find `const {const_name} =` backtick-literal start")
    start = m.end()
    end = js_text.rfind("`;")
    if end == -1 or end < start:
        raise ValueError(f"Could not find closing backtick for {const_name}")
    content = js_text[start:end]
    # Neutralize accidental triple-quote collisions and stray backslashes so the
    # Python triple-quoted string stays valid.
    content = content.replace("\\", "\\\\").replace(TRIPLE, '\\"\\"\\"')
    return content


def main():
    parts = [
        '"""Study-abroad knowledge base, ported from Desktop/Counselor/knowledge/*.js.',
        '',
        'Mechanically generated by scripts/port_knowledge_base.py -- re-run that script',
        'to refresh this file if the source .js knowledge base is edited. Do not hand-edit',
        'the KB_* constants directly; edit the source .js files and re-run the script instead.',
        '"""',
        '',
    ]
    for filename, const_name in FILES:
        path = os.path.join(COUNSELOR_KB_DIR, filename)
        with open(path, "r", encoding="utf-8") as f:
            js_text = f.read()
        content = extract(js_text, const_name)
        parts.append(f'{const_name} = {TRIPLE}{content}{TRIPLE}')
        parts.append('')
        print(f"Ported {const_name} ({len(content)} chars) from {filename}")

    with open(OUT_PATH, "w", encoding="utf-8") as f:
        f.write("\n".join(parts))
    print(f"\nWrote {OUT_PATH}")


if __name__ == "__main__":
    main()
